### ISSUE TITLE
Error when importing some Sonic Colors terrain meshes

### ISSUE THREAD

**Issue by RobowilOFFICIAL** [hayden0729/berrybush#11]
I'm trying to get all of Tropical Resort Act 1/2 terrain into Blender with this plugin. While it's going smooth for the most part, I get an error with at least three of the terrain meshes (14, 23 and 25). I'm entirely unsure what's specifically causing this as well. This is the error message I got when importing 14, and I got essentially the same one for 23 and 25.

![Screenshot 2024-08-24 213807](https://github.com/user-attachments/assets/741ac85b-038d-4c57-aa93-f7ea5100dcc8)

The files that cause the error to occur: https://drive.google.com/file/d/1T3n41JUe1Ruh-RipKo9VxsHpsbyc5KrT/view?usp=sharing

Is there a workaround for this error, or will this need to be fixed in a future update?

**Comment by hayden0729** [comment]
Hi, thanks for the report! I'm not sure what's causing this yet, but it seems like a bug relating to the "Multi-Material Meshes" import option. Until this is fixed, disabling that option seems to be the way around it.
![image](https://github.com/user-attachments/assets/9dfc89a2-7f8c-44c0-8b95-084bd3e8ca90)

**Comment by hayden0729** [comment]
Should be fixed in [1.4.5](https://github.com/hayden0729/berrybush/releases/tag/1.4.5) - let me know if you have any other issues.

**Comment by RobowilOFFICIAL** [comment]
I have tested it with the same meshes that caused the error, and they now import properly! Thanks!
![{224F50A2-4939-4035-8E2B-C91EDA0CAE2C}](https://github.com/user-attachments/assets/a255e7b8-c07f-4657-b3d8-7fd32b25195d)
