### ISSUE TITLE
Feature request: Ability to render image/video with transparency

### ISSUE THREAD

**Issue by EthonicDev** [hayden0729/berrybush#3]
This isn't important for berrybush's main use, but i was going to render something with transparency, I was looking around in it, and i cannot find a way to render a transparent image/video. In eevee and cycles, they have a film section where you can enable transparent background, 
![image](https://github.com/hayden0729/berrybush/assets/125166775/4c8f886e-a817-4c16-869d-7367b61d263c)
![image](https://github.com/hayden0729/berrybush/assets/125166775/71984b09-e064-4271-a9b2-2f82f7ecb21a)
![image](https://github.com/hayden0729/berrybush/assets/125166775/a9223964-0b64-4bfe-b68b-94425d6fa09f)

**Comment by EthonicDev** [comment]
Nevermind, it just renders with transparency by default! although it would maybe be nice to make transparency an option.

This is what i was trying to make(but compressed a lot so i can post it here) the black part in the beginning is transparent in the full render.
https://github.com/hayden0729/berrybush/assets/125166775/f398996d-078e-4f96-afbf-5d067939c9d5

**Comment by hayden0729** [comment]
Hey, thanks for using the tool! This is indeed not BerryBush’s main use, but it’s a cool one and I’ll look into adding some basic settings like optional transparency for rendering. Sweet render btw.
