### ISSUE TITLE
Bone scale is not reset to (1, 1, 1)

### ISSUE THREAD

**Issue by Synell** [hayden0729/berrybush#5]
I have a model with a scale of (16, 16, 16):

![image](https://github.com/hayden0729/berrybush/assets/70210528/8ef19440-3bcc-473e-921b-7a7a19ce0ede)

And when I open it with berrybush the scale is reset to (1, 1, 1):

![image](https://github.com/hayden0729/berrybush/assets/70210528/bb5bab19-9379-439d-9fe9-fc8241d0f3b8)

So when I export the brres, the scale is also reset to (1, 1, 1) in the exported file.
(And in that case, I can't really rescale it and apply the transforms in blender as it breaks some positions in a weird way)

Not a huge issue because I can post edit the scale again with brawlcrate but just wanted to let you know about this small bug. ^^

**Comment by hayden0729** [comment]
Hey, thanks for the report. It looks like you have the armature selected in Object Mode. Can you see scaling on the bone if you switch to Pose Mode?

**Comment by hayden0729** [comment]
Alright, thanks. Have you tried enabling the "Use Current Pose" checkbox in the export options? I think this should fix the issue.

![image](https://github.com/hayden0729/berrybush/assets/69529462/8c190afa-d9d5-40eb-b7e2-73858c8ee4d4)

**Comment by Synell** [comment]
Ah I didn't, it works fine with this option checked, thanks ! :)

![image](https://github.com/hayden0729/berrybush/assets/70210528/17b13115-3050-4e48-8916-54350380bba6)

Sorry for the false issue then. 😅
