### ISSUE TITLE
Error when importing.

### ISSUE THREAD

**Issue by LandonAndEmma** [hayden0729/berrybush#9]
Here's my file and error. I'm using Blender 3.3 LTS
[error.txt](https://github.com/user-attachments/files/16019014/error.txt)
[https://www.mediafire.com/file/rymj1v549v99l0y/Tsuruya.7z/file](url)

**Comment by hayden0729** [comment]
Hey, thanks for the report. This looks like a duplicate of #8, so you can follow the steps listed there to troubleshoot. The error message tells you which texture is problematic ('ToonTex_02' of material 'body_up_000'), so you'll have to change that texture's settings in BrawlCrate. If there are any other textures with issues, it'll tell you after you've fixed that one.

**Comment by LandonAndEmma** [comment]
Okay thank you
